{{- if .Values.config.route.enabled -}}
{{- $fullName := include "comp1.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "comp1.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  port:
    targetPort: {{ $svcPort }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  wildcardPolicy: None
{{- end }}