# demo-helm-201: TEST stage


image:
  tag: "1.0.1"

service:
  type: ClusterIP
  port: 8001

# Example for with and range showcase
serviceAccounts:
  commonLable: demo-common-label
  names:
  - name: demo-app-s1-sa
    lable: demo1
  - name: demo-app-s2-sa
    lable: demo2